---
title: "P2ry12 KEGG pathway"
author: "yincy"
date: "11/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(ggraph)
library(tidygraph)
library(igraph)
library(stringr)
library(stringr.plus)
library(EnsDb.Mmusculus.v79)
library(org.Mm.eg.db)
library(tidyverse)
```

# load data  
```{r}
#pvn <- read.csv(file = "../data/20201109_frame_tpm_PVN.csv", row.names = 1)
```

# samples  
```{r}
# A14 <- grep("14A", colnames(pvn), value = T)
# L14 <- grep("14L", colnames(pvn), value = T)
# A3 <- grep("3A", colnames(pvn), value = T)
# L3 <- grep("3L", colnames(pvn), value = T)
# naive <- grep("naive", colnames(pvn), value = T)
# 
# A14;L14;A3;L3;naive
# 
# 
# # sample column index
# pvn_A14_col_index <- grep(str_c(A14, collapse = "|"), colnames(pvn))
# pvn_L14_col_index <- grep(str_c(L14, collapse = "|"), colnames(pvn))
# pvn_A3_col_index <- grep(str_c(A3, collapse = "|"), colnames(pvn))
# pvn_L3_col_index <- grep(str_c(L3, collapse = "|"), colnames(pvn))
# pvn_naive_col_index <- grep(str_c(naive, collapse = "|"), colnames(pvn))
```


```{r}
# PVN Top 100 GO DEGs
# files <- list.files(path = "../data/20201204/", pattern = "GO_down|GO_up", full.names = T)
# sheets <- c("PVN_3L", "PVN_3A")
# outs <- paste(rep(c("PVN_3L", "PVN_3A"), 2), rep(c("down", "up"), each = 2), sep = "_")
# 
# pvn <- list()
# 
# k = 0
# for(i in seq_along(files)){
#   for(j in seq_along(sheets)){
#     x <- readxl::read_xlsx(path = files[i], sheet = sheets[j]) %>% 
#       tibble::as_tibble() %>% 
#       dplyr::arrange(pvalue) %>% 
#       head(100) %>% 
#       dplyr::pull(geneID) %>% 
#       stringr::str_c(collapse = "/") %>% 
#       stringr::str_split(pattern = "/") %>% 
#       .[[1]] %>% 
#       unique()
#     k = k + 1
#     pvn[[outs[k]]] <- x
#   }
# }
# 
# df <- pvn %>% 
#   unlist() %>% 
#   as.data.frame() %>% 
#   tibble::rownames_to_column("group") %>% 
#   magrittr::set_colnames(c("group", "symbol"))
# 
# df$group <- gsub("[0-9]{,3}$", "", df$group)
# 
# write.csv(x = df, file = "../res/P2ry12/top100_GO_DEGs.csv")
```

```{r}
# table(df$symbol %in% inter_3)
# 
# all_DEG <- intersect(inter_3, df$symbol)
```


```{r}
# PVN common up and down genes
pvn3_common_up_genes <- readxl::read_xlsx("../data/20201204_common/20201204_geneid_up_common_list.xlsx", 
                                        sheet = "PVN_3") %>% 
  pull(up_PVN_3) %>% 
  as.character()

pvn3_common_down_genes <- readxl::read_xlsx("../data/20201204_common/20201204_geneid_down_common_list.xlsx", 
                                          sheet = "PVN_3") %>% 
  pull(down_PVN_3) %>% 
  as.character()

# BS common up and down genes
BS3_common_up_genes <- readxl::read_xlsx("../data/20201204_common/20201204_geneid_up_common_list.xlsx", 
                                        sheet = "BS_3") %>% 
  pull(up_BS_3) %>% 
  as.character()

BS3_common_down_genes <- readxl::read_xlsx("../data/20201204_common/20201204_geneid_down_common_list.xlsx", 
                                          sheet = "BS_3") %>% 
  pull(down_BS_3) %>% 
  as.character()

# CTX common up and down genes
CTX3_common_up_genes <- readxl::read_xlsx("../data/20201204_common/20201204_geneid_up_common_list.xlsx", 
                                         sheet = "CTX_3") %>% 
  pull(up_CTX_3) %>% 
  as.character()

CTX3_common_down_genes <- readxl::read_xlsx("../data/20201204_common/20201204_geneid_down_common_list.xlsx", 
                                           sheet = "CTX_3") %>% 
  pull(down_CTX_3) %>% 
  as.character()


degs <- c(pvn3_common_up_genes, pvn3_common_down_genes, 
          BS3_common_up_genes, BS3_common_down_genes, 
          CTX3_common_up_genes, BS3_common_down_genes)

"Cop1" %in% degs %>% sort()
```


# DEG file from weibo
```{r}
tpm_20201113 <- read.table("../data/20201113_frame_tpm BO.csv", 
                           row.names = 1, 
                           header = T, 
                           sep = ",")

# remove 14 day data
tpm_20201113 <- tpm_20201113 %>% 
  select(-contains("_14"))

# filter out low expressed genes
bs_filter_index <- tpm_20201113[, grep("^BS", colnames(tpm_20201113))] %>% 
  apply(1, FUN = function(x){sum(x > 0.5) > 4})
ctx_filter_index <- tpm_20201113[, grep("^CTX", colnames(tpm_20201113))] %>% 
  apply(1, FUN = function(x){sum(x > 0.5) > 4})
pvn_filter_index <- tpm_20201113[, grep("^PVN", colnames(tpm_20201113))] %>% 
  apply(1, FUN = function(x){sum(x > 0.5) > 4})

filter_index <- bs_filter_index | ctx_filter_index | pvn_filter_index
tpm_20201113 <- tpm_20201113[filter_index, ]

# get sample index
BS_naive_index <- grep("^BS_Naive[0-9]{1}", colnames(tpm_20201113), value = T)
BS_3L_index <- grep("^BS_3L[0-9]{1}", colnames(tpm_20201113), value = T)
BS_3A_index <- grep("^BS_3A[0-9]{1}", colnames(tpm_20201113), value = T)

CTX_naive_index <- grep("^CTX_Naive[0-9]{1}", colnames(tpm_20201113), value = T)
CTX_3L_index <- grep("^CTX_3L[0-9]{1}", colnames(tpm_20201113), value = T)
CTX_3A_index <- grep("^CTX_3A[0-9]{1}", colnames(tpm_20201113), value = T)

PVN_naive_index <- grep("^PVN_Naive[0-9]{1}", colnames(tpm_20201113), value = T)
PVN_3L_index <- grep("^PVN_3L[0-9]{1}", colnames(tpm_20201113), value = T)
PVN_3A_index <- grep("^PVN_3A[0-9]{1}", colnames(tpm_20201113), value = T)

# differential expressed genes based on fold change
tpm_20201113 <- tpm_20201113 %>% 
  rowwise() %>% 
  mutate(mean_BS_naive = mean(c(BS_Naive1, BS_Naive1, BS_Naive3), na.rm = T), 
         mean_BS_3L = mean(c(BS_3L3, BS_3L4, BS_3L5), na.rm = T), 
         mean_BS_3A = mean(c(BS_3A5, BS_3A6, BS_3A7), na.rm = T), 
         mean_CTX_naive = mean(c(CTX_Naive1, CTX_Naive2, CTX_Naive3), na.rm = T), 
         mean_CTX_3L = mean(c(CTX_3L2, CTX_3L3, CTX_3L4), na.rm = T), 
         mean_CTX_3A = mean(c(CTX_3A2, CTX_3A3, CTX_3A4), na.rm = T), 
         mean_PVN_naive = mean(c(PVN_Naive1, PVN_Naive2, PVN_Naive3), an.rm = T), 
         mean_PVN_3L = mean(c(PVN_3L1_b1, PVN_3L2_b1, PVN_3L3), na.rm = T), 
         mean_PVN_3A = mean(c(PVN_3A1_b1, PVN_3A2, PVN_3A3_b1)), 
         flc_BS_3L = (mean_BS_3L / mean_BS_naive) %>% round(digits = 3), 
         flc_BS_3A = (mean_BS_3A / mean_BS_naive) %>% round(digits = 3), 
         flc_CTX_3L = (mean_CTX_3L / mean_CTX_naive) %>% round(digits = 3), 
         flc_CTX_3A = (mean_CTX_3A / mean_CTX_naive) %>% round(digits = 3), 
         flc_PVN_3L = (mean_PVN_3L / mean_PVN_naive) %>% round(digits = 3), 
         flc_PVN_3A = (mean_PVN_3A / mean_PVN_naive) %>% round(digits = 3))

BS_common_up <- tpm_20201113 %>% 
  filter(flc_BS_3A >= 2 & flc_BS_3L >= 2) %>% 
  pull(geneid_symbol) %>% 
  unique()
BS_common_down <- tpm_20201113 %>% 
  filter(flc_BS_3A <= 0.5 & flc_BS_3L <= 0.5) %>% 
  pull(geneid_symbol) %>% 
  unique()

CTX_common_up <- tpm_20201113 %>% 
  filter(flc_CTX_3A >= 2, flc_CTX_3L >= 2) %>% 
  pull(geneid_symbol) %>% 
  unique()
CTX_common_down <- tpm_20201113 %>% 
  filter(flc_CTX_3A <= 0.5 & flc_CTX_3L <= 0.5) %>% 
  pull(geneid_symbol) %>% 
  unique()

PVN_common_up <- tpm_20201113 %>% 
  filter(flc_PVN_3A >=2 & flc_PVN_3L >= 2) %>% 
  pull(geneid_symbol) %>% 
  unique()
PVN_common_down <- tpm_20201113 %>% 
  filter(flc_PVN_3A <= 0.5 & flc_PVN_3L <= 0.5) %>% 
  pull(geneid_symbol) %>% 
  unique()
```


```{r}
tpm_20201113 %>% 
  filter(geneid_symbol %in% c("Cop1", "Cebpb", "P2ry12", "Mapk11", "Mapk1", "Trp53")) %>%
  write.csv(file = "../res/P2ry12/flc.csv")
```


## Veen   
```{r}
# library(VennDiagram)
# ?venn.diagram
# 
# venn.diagram(x = list(A3_L3_inter = inter_3, A14_L14_inter = inter_14), 
#              filename = "../res/P2ry12/A3_L3_A14_L14_Venn.tiff", 
#              resolution = 1000, 
#              cex = 0.5, 
#              height = 5000, 
#              width = 5000)
```


# load KEGG pathway  
```{r}
# all_path_df <- read.csv(file = "../res/P2ry12/all_pathways_df.csv", 
#                         stringsAsFactors = F)
all_path_df <- readRDS("../data/KEGG/KEGG_pathways_formatted.rds")
names_to_display <- readRDS("../data/KEGG/names_to_display.rds")

all_path_df %>% dim()
all_path_df %>% pull(type) %>% table()
all_path_df %>% pull(subtype) %>% table()

all_path_df %>% head()
all_path_df <- all_path_df %>% distinct(from, to, .keep_all = T)
all_path_df %>% dim()

all_path_df %>% 
  dplyr::filter(type == "maplink")

all_path_df <- all_path_df %>% 
  dplyr::filter(type != "maplink")
all_path_df %>% dim()

all_path_df$from <- gsub("mmu:", replacement = "", all_path_df$from)
all_path_df$to <- gsub("mmu:", replacement = "", all_path_df$to)

all_path_df %>% dim()
all_path_df %>% head()
```


# Visualization  
```{r}
pvn3_entrez <- mapIds(org.Mm.eg.db, 
                      keys = c(PVN_common_down, PVN_common_up), 
                      keytype = "SYMBOL", 
                      column = "ENTREZID") %>% 
  na.omit() %>% 
  as.character()

CTX3_entrez <- mapIds(org.Mm.eg.db, 
                      keys = c(CTX_common_down, CTX_common_up), 
                      keytype = "SYMBOL", 
                      column = "ENTREZID") %>% 
  na.omit() %>% 
  as.character()

BS3_entrez <- mapIds(org.Mm.eg.db, 
                    keys = c(BS_common_down, BS_common_up), 
                    keytype = "SYMBOL", 
                    column = "ENTREZID")


ig <- graph_from_data_frame(d = all_path_df, directed = T)

spath_pvn3 <- shortest_paths(graph = ig, 
                        from = V(ig)$name == "70839", 
                        to = V(ig)$name %in% pvn3_entrez, 
                        output = "epath",
                        mode = "out") %>% 
  .$epath

spath_CTX3 <- shortest_paths(graph = ig, 
                             from = V(ig)$name == "70839", 
                             to = V(ig)$name %in% CTX3_entrez, 
                             output = "epath", 
                             mode = "out") %>% 
  .$epath

spath_BS3 <- shortest_paths(ig, 
                            from = V(ig)$name == "70839", 
                            to = V(ig)$name %in% BS3_entrez, 
                            output = "epath", 
                            mode = "out") %>% 
  .$epath

# pathways between COP1 (RFWD2) and Cebpb
# 
# mapIds(EnsDb.Mmusculus.v79, 
#        keys = c("Cebpb", "Rfwd2", "P2ry12"), 
#        keytype = "SYMBOL", 
#        column = "ENTREZID")
# 
# spath_Cop1_Cebpb <- shortest_paths(ig, 
#                                    from = V(ig)$name == "26374", 
#                                    to = V(ig)$name == "12608", 
#                                    mode = "all", 
#                                    output = "epath") %>% 
#   .$epath
# 
# spath_p2ry12_Cop1_Cebpb <- shortest_paths(ig, 
#                                           from = V(ig)$name == "70839", 
#                                           to = V(ig)$name %in% c("12608", "26374"), 
#                                           mode = "all", 
#                                           output = "epath") %>% 
#   .$epath
```


```{r}
spath_df_pvn3 <- spath_pvn3 %>% 
  sapply(as_ids) %>% 
  lapply(as.matrix) %>% 
  unlist() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames("from_to") %>% 
  separate(col = "from_to", into = c("from", "to"), sep = "\\|") %>% 
  distinct(from, to)

spath_df_CTX3 <- spath_CTX3 %>% 
  sapply(as_ids) %>% 
  lapply(as.matrix) %>% 
  unlist() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames("from_to") %>% 
  separate(col = "from_to", into = c("from", "to"), sep = "\\|") %>% 
  distinct(from, to)

spath_df_BS3 <- spath_BS3 %>% 
  sapply(as_ids) %>% 
  lapply(as.matrix) %>% 
  unlist() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames("from_to") %>% 
  separate(col = "from_to", into = c("from", "to"), sep = "\\|") %>% 
  distinct(from, to)

# pathways between COP1 and Cebpb
# spath_Cop1_Cebpb_df <- spath_Cop1_Cebpb %>% 
#   sapply(as_ids) %>% 
#   lapply(as.matrix) %>% 
#   unlist %>% 
#   as.data.frame() %>% 
#   magrittr::set_colnames("from_to") %>% 
#   separate(col = "from_to", into = c("from", "to"), sep = "\\|") %>% 
#   distinct(from, to)
# 
# spath_p2ry12_Cop1_Cebpb_df <- spath_p2ry12_Cop1_Cebpb %>% 
#   sapply(as_ids) %>% 
#   lapply(as.matrix) %>% 
#   unlist %>% 
#   as.data.frame() %>% 
#   magrittr::set_colnames("from_to") %>% 
#   separate(col = "from_to", into = c("from", "to")) %>% 
#   distinct(from, to)
# 
# # combine the two 
# p2ry12_cop1_Cebpb <- rbind(spath_Cop1_Cebpb_df, spath_p2ry12_Cop1_Cebpb_df) %>% distinct(from, to)
```


```{r}
spath_df_pvn3_KEGG <- left_join(spath_df_pvn3, all_path_df, by = c("from" = "from", "to" = "to")) %>% 
  distinct(from, to, .keep_all  =T)

spath_df_BS3_KEGG <- left_join(spath_df_BS3, all_path_df, by = c("from" = "from", "to" = "to")) %>% 
  distinct(from, to, .keep_all = T)

spath_df_CTX3_KEGG <- left_join(spath_df_CTX3, all_path_df, by = c("from" = "from", "to" = "to")) %>% 
  distinct(from, to, .keep_all = T)

# pathways between COP1 and Cebpb
# p2ry12_cop1_Cebpb_df <- left_join(p2ry12_cop1_Cebpb, 
#                                  all_path_df, 
#                                  by = c("from" = "from", "to" = "to")) %>% 
#   distinct(from, to, .keep_all = T)
```

add node color
```{r}
# pvn3
N_pvn3 <- tibble(
  ids = c(spath_df_pvn3_KEGG$from, spath_df_pvn3_KEGG$to) %>% unique()
) %>% 
  mutate(shape = ifelse(grepl("^cpd:|^gl:|^dr:", ids, ignore.case = F), "22", "21"), 
         ncol = "grey", 
         ncol = ifelse(names_to_display[ids] %in% pvn3_common_up_genes, "darkred", ncol), 
         ncol = ifelse(names_to_display[ids] %in% pvn3_common_down_genes, "darkblue", ncol))

E_pvn3 <- spath_df_pvn3_KEGG 


# BS3
N_BS3 <- tibble(
  ids = c(spath_df_BS3_KEGG$from, spath_df_BS3_KEGG$to) %>% unique()
) %>% 
  mutate(shape = ifelse(grepl("^cpd:|^gl:|^dr:", ids, ignore.case = F), "22", "21"), 
         ncol = "grey", 
         ncol = ifelse(names_to_display[ids] %in% BS3_common_up_genes, "darkred", ncol), 
         ncol = ifelse(names_to_display[ids] %in% BS3_common_down_genes, "darkblue", ncol))

E_BS3 <- spath_df_BS3_KEGG

# CTX3
N_CTX3 <- tibble(
  ids = c(spath_df_CTX3_KEGG$from, spath_df_CTX3_KEGG$to) %>% unique()
) %>% 
  mutate(shape = ifelse(grepl("^cpd:|^gl:|^dr:", ids, ignore.case = F), "22", "21"), 
         ncol = "grey", 
         ncol = ifelse(names_to_display[ids] %in% CTX3_common_up_genes, "darkred", ncol), 
         ncol = ifelse(names_to_display[ids] %in% CTX3_common_down_genes, "darkblue", ncol))

E_CTX3 <- spath_df_CTX3_KEGG
```


downstream of Mapk1, Mapk11, Pik3ca, Pla2g4b, Pla2g4a
```{r}
tg <- as_tbl_graph(all_path_df)

gs <- c("Mapk1", "Mapk11", "Pik3ca", "Pla2g4b", "Pla2g4a")
names_to_display[names_to_display %in% gs]
dist <- 2

mapk11_downstream <- tg %>% 
  mutate(ids = name,  
         names = names_to_display[ids], 
         dist_mapk11 = bfs_dist(.N()$ids == "19094", mode = "out")) %>% 
  select(-name) %>% 
  filter(dist_mapk11 <= dist) %>% 
  arrange(dist_mapk11) %>% 
  filter(!node_is_isolated()) %>% 
  activate(edges) %>% 
  filter(!edge_is_loop())

mapk1_downstream <- tg %>% 
  mutate(ids = name, 
         names = names_to_display[ids], 
         dist_mapk1 = bfs_dist(.N()$ids == "26413", mode = "out")) %>% 
  select(-name) %>% 
  filter(dist_mapk1 <= dist) %>% 
  arrange(dist_mapk1) %>% 
  filter(!node_is_isolated()) %>% 
  activate(edges) %>% 
  filter(!edge_is_loop())


pik3ca_downstream <- tg %>% 
  mutate(ids = name, 
         names = names_to_display[ids], 
         dist_pik3ca = bfs_dist(.N()$ids == "18706", mode = "out")) %>% 
  select(-name) %>% 
  filter(dist_pik3ca <= dist) %>% 
  arrange(dist_pik3ca) %>% 
  filter(!node_is_isolated()) %>% 
  activate(edges) %>% 
  filter(!edge_is_loop())

pla2g4a_downstream <- tg %>% 
  mutate(ids = name, 
         names = names_to_display[ids], 
         dist_pla2g4a = bfs_dist(.N()$ids == "18783", mode = "out")) %>% 
  select(-name) %>% 
  filter(dist_pla2g4a <= dist) %>% 
  arrange(dist_pla2g4a) %>% 
  filter(!node_is_isolated()) %>% 
  activate(edges) %>% 
  filter(!edge_is_loop())

pla2g4b_downstream <- tg %>% 
  mutate(ids = name, 
         names = names_to_display[ids], 
         dist_pla2g4b = bfs_dist(.N()$ids == "211429", mode = "out")) %>% 
  select(-name) %>% 
  filter(dist_pla2g4b <= dist) %>% 
  arrange(dist_pla2g4b) %>% 
  filter(!node_is_isolated()) %>% 
  activate(edges) %>% 
  filter(!edge_is_loop())

joined <- pla2g4a_downstream %>% 
  graph_join(pla2g4b_downstream, by = c("ids" = "ids", "names" = "names")) %>% 
  graph_join(mapk1_downstream, by = c("ids" = "ids", "names" = "names")) %>% 
  graph_join(mapk11_downstream, by = c("ids" = "ids", "names" = "names")) %>% 
  graph_join(pik3ca_downstream, by = c("ids" = "ids", "names" = "names"))
```


```{r}
pla2g4b_downstream %>% 
  as.data.frame() %>% 
  write.xlsx(file = "../res/P2ry12/downstream_genes.xlsx", sheetName = "pla2g4b", append = T)
```


combine the graph  
```{r}
df <- rbind(spath_df_pvn3_KEGG, spath_df_BS3_KEGG, spath_df_CTX3_KEGG) 

N <- tibble(
  ids = c(df$from, df$to) %>% unique()
) %>% 
  mutate(
    shape = ifelse(grepl("^cpd:|^gl:|^dr:", ids, ignore.case = F), "22", "21"), 
    ncol = "grey", 
    group = ifelse(names_to_display[ids] %in% c(pvn3_common_down_genes, pvn3_common_up_genes), "PVN", ""), 
    ncol_pvn = ifelse(names_to_display[ids] %in% pvn3_common_up_genes, "darkred", ncol), 
    ncol_pvn = ifelse(names_to_display[ids] %in% pvn3_common_down_genes, "darkblue", ncol)
  )

E <- df

df$from_symbol <- names_to_display[df$from]
df$to_symbol <- names_to_display[df$to]

# df %>% 
#   distinct(from, to, .keep_all = T) %>% 
#   select(from_symbol, to_symbol, everything(), -from, -to) %>% 
#   write.csv(file = "../res/P2ry12/comined_path-20210411.csv", row.names = F, quote = F, na = "")
```


```{r}
g_pvn3 <- tbl_graph(nodes = N_pvn3, edges = E_pvn3, directed = T)
g_BS3 <- tbl_graph(nodes = N_BS3, edges = E_BS3, directed = T)
g_CTX3 <- tbl_graph(nodes = N_CTX3, edges = E_CTX3, directed = T)

## pathways between COP1 and Cebpb
# g_Cop1_Cebpb <- tbl_graph(nodes = data.frame(ids = unique(c(p2ry12_cop1_Cebpb_df$from, p2ry12_cop1_Cebpb_df$to))), 
#                           edges = p2ry12_cop1_Cebpb_df, 
#                           directed = T)
```

```{r, warning=F, message=F}
set.seed(123)
g_pvn3 %>% 
  mutate(name = names_to_display[ids], 
         shape = factor(shape)) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == 30), 
                     edge_linetype = lty),
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm"))) +
  geom_edge_link(aes(filter = (angle == 90), 
                     edge_linetype = lty), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm"))) +
  geom_edge_link(aes(filter = (is.na(angle)), 
                     edge_linetype = lty)) +
  geom_node_point(aes(shape = shape, color = ncol), 
                  size = 5) +
  geom_node_text(aes(label = names_to_display[.N()$ids]), size = 2) +
  scale_color_manual(name = NULL, 
                     values = c("darkred" = "darkred", "darkblue" = "darkblue", "grey" = "grey"), 
                     labels = c("down", "up", "not significant")) +
  scale_edge_linetype_manual(values = c("1" = "solid", "5" = "dotted")) +
  guides(edge_linetype = F, shape = F)

ggsave("../res/P2ry12/20210303-pvn3.pdf")
```

```{r}
set.seed(123)
g_BS3 %>% 
  mutate(name = names_to_display[ids], 
         shape = factor(shape)) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == 30), 
                     edge_linetype = lty),
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm"))) +
  geom_edge_link(aes(filter = (angle == 90), 
                     edge_linetype = lty), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm"))) +
  geom_edge_link(aes(filter = (is.na(angle)), 
                     edge_linetype = lty)) +
  geom_node_point(aes(shape = shape, color = ncol), 
                  size = 5) +
  geom_node_text(aes(label = names_to_display[.N()$ids]), size = 2) +
  scale_color_manual(name = NULL, 
                     values = c("darkred" = "darkred", "darkblue" = "darkblue", "grey" = "grey"), 
                     labels = c("down", "up", "not significant")) +
  scale_edge_linetype_manual(values = c("1" = "solid", "5" = "dotted")) +
  guides(edge_linetype = F, shape = F)

ggsave("../res/P2ry12/20210303-BS3.pdf")
```


```{r}
set.seed(123)
g_CTX3 %>% 
  mutate(name = names_to_display[ids], 
         shape = factor(shape)) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == 30), 
                     edge_linetype = lty),
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm"))) +
  geom_edge_link(aes(filter = (angle == 90), 
                     edge_linetype = lty), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm"))) +
  geom_edge_link(aes(filter = (is.na(angle)), 
                     edge_linetype = lty)) +
  geom_node_point(aes(shape = shape, color = ncol), 
                  size = 5) +
  geom_node_text(aes(label = names_to_display[.N()$ids]), size = 2) +
  scale_color_manual(name = NULL, 
                     values = c("darkred" = "darkred", "darkblue" = "darkblue", "grey" = "grey"), 
                     labels = c("down", "up", "not significant")) +
  scale_edge_linetype_manual(values = c("1" = "solid", "5" = "dotted")) +
  guides(edge_linetype = F, shape = F)

ggsave("../res/P2ry12/20210303-CTX3.pdf")
```


combine all pathways
```{r, message=FALSE, warning=FALSE}
g <- tbl_graph(nodes = N, edges = E, directed = T)
g <- g %>% 
  filter(!node_is_isolated()) %>% 
  activate(edges) %>% 
  filter(!edge_is_loop()) %>% 
  activate(nodes)

full_graph <- graph_join(joined, g, by = c("ids" = "ids", "names" = "names"))
full_graph <- full_graph %>% 
  select(-starts_with("dist"), -starts_with("ncol"), -shape, -group) %>% 
  mutate(shape = ifelse(grepl("^cpd:|^gl:|^dr:", ids, ignore.case = F), "22", "21"))


ll <- create_layout(full_graph, layout = "igraph", algorithm = "tree", mode = "out")
ll$x <- ll$x * 5
ll$y <- ll$y * 5



full_graph %>% 
  ggraph(layout = "dendrogram") +
  geom_edge_diagonal(aes(filter = (subtype == "inhibition")), 
                 end_cap = circle(2, "mm"), 
                 start_cap = circle(2, "mm"), 
                 arrow = arrow(angle = 90, length = unit(2, "mm")))

g %>% 
  ggraph(layout = "dendrogram") +
  geom_edge_diagonal(aes(filter = (subtype == "inhibition")),
                     arrow = arrow(angle = 90, length = unit(3, "mm")), 
                     end_cap = circle(2, "mm")) +
  geom_node_point(size = 4, col = "grey80") +
  geom_node_text(aes(label = .N()$names), size = 1)

ggsave("dendrogram.tiff")
```

```{r}
full_graph %>% 
  activate(edges) %>% 
  as.data.frame() %>% 
  pull(subtype) %>% table(useNA = "ifany")
```


```{r, message=FALSE, warning=FALSE}
set.seed(123)
g %>% 
  mutate(
    name = names_to_display[ids], 
    shape = factor(shape), 
    ncol = "not significant",
    ncol = ifelse(name %in% pvn3_common_up_genes, "up", ncol), 
    ncol = ifelse(name %in% pvn3_common_down_genes, "down", ncol), 
    ncol = factor(ncol, levels = c("up", "down", "not significant"))
  ) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "treemap") +
  geom_edge_link(aes(filter = (angle == 30), 
                     edge_linetype = lty, 
                     label = edge_label), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm")), 
                 edge_width = 0.1) +
  geom_edge_link(aes(filter = (angle == 90), 
                     edge_linetype = lty, 
                     label = edge_label),
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm")), 
                 edge_width = 0.1) +
  geom_edge_link(aes(filter = (is.na(angle)), 
                     edge_linetype = lty, 
                     label = edge_label), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 edge_width = 0.1) +
  geom_node_point(aes(shape = shape, color = ncol), size = 2) +
  geom_node_text(aes(label = name), size = 1.2) +
  scale_color_manual(name = NULL, values = c("up" = "darkred", "down" = "darkblue", "not significant" = "grey")) +
  guides(edge_linetype = F, shape = F) +
  theme_graph()

ggsave("../res/p2ry12_downstream_signal_pvn3_combined_20210622.pdf", device = cairo_pdf)
```


```{r, message=FALSE, warning=FALSE}
set.seed(123)
g %>% 
  mutate(
    name = names_to_display[ids], 
    shape = factor(shape), 
    ncol = "not significant",
    ncol = ifelse(name %in% BS3_common_up_genes, "up", ncol), 
    ncol = ifelse(name %in% BS3_common_down_genes, "down", ncol), 
    ncol = factor(ncol, levels = c("up", "down", "not significant"))
  ) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == 30), 
                     edge_linetype = lty, 
                     label = edge_label), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm")), 
                 edge_width = 0.1) +
  geom_edge_link(aes(filter = (angle == 90), 
                     edge_linetype = lty, 
                     label = edge_label),
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm")), 
                 edge_width = 0.1) +
  geom_edge_link(aes(filter = (is.na(angle)), 
                     edge_linetype = lty, 
                     label = edge_label), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 edge_width = 0.1) +
  geom_node_point(aes(shape = shape, color = ncol), size = 5) +
  geom_node_text(aes(label = name), size = 1.2) +
  scale_color_manual(name = NULL, values = c("up" = "darkred", "down" = "darkblue", "not significant" = "grey")) +
  guides(edge_linetype = F, shape = F) +
  theme_graph()

ggsave("../res/p2ry12_downstream_signal_BS3_combined_20210327.pdf", device = cairo_pdf)
```

```{r, message=FALSE, warning=FALSE}
set.seed(123)
g %>% 
  mutate(
    name = names_to_display[ids], 
    shape = factor(shape), 
    ncol = "not significant",
    ncol = ifelse(name %in% CTX3_common_up_genes, "up", ncol), 
    ncol = ifelse(name %in% CTX3_common_down_genes, "down", ncol), 
    ncol = factor(ncol, levels = c("up", "down", "not significant"))
  ) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == 30), 
                     edge_linetype = lty, 
                     label = edge_label), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm")), 
                 edge_width = 0.1) +
  geom_edge_link(aes(filter = (angle == 90), 
                     edge_linetype = lty, 
                     label = edge_label),
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(1, "mm")), 
                 edge_width = 0.1) +
  geom_edge_link(aes(filter = (is.na(angle)), 
                     edge_linetype = lty, 
                     label = edge_label), 
                 end_cap = circle(2.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 edge_width = 0.1) +
  geom_node_point(aes(shape = shape, color = ncol), size = 5) +
  geom_node_text(aes(label = name), size = 1.2) +
  scale_color_manual(name = NULL, values = c("up" = "darkred", "down" = "darkblue", "not significant" = "grey")) +
  guides(edge_linetype = F, shape = F) +
  theme_graph()

ggsave("../res/p2ry12_downstream_signal_CTX3_combined_20210327.pdf", device = cairo_pdf)
```

```{r}
## pathways between COP1 and Cebpb

set.seed(123)
g_Cop1_Cebpb %>% 
  mutate(name = names_to_display[ids]) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == 30), 
                     edge_linetype = lty, 
                     label = .E()$subtype),
                 end_cap = circle(5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(2, "mm")), 
                 label_size = 2, 
                 angle_calc = "along", 
                 label_dodge = unit(2.5, "mm")) +
  geom_edge_link(aes(filter = (angle == 90),
                     edge_linetype = lty,
                     label = .E()$subtype),
                 end_cap = circle(5, "mm"),
                 start_cap = circle(1, "mm"),
                 arrow = arrow(angle = 90, length = unit(2, "mm")),
                 label_size = 3,
                 angle_calc = "along",
                 label_dodge = unit(2.5, "mm")) +
  geom_node_point(size = 10, color = "grey70") +
  geom_node_text(aes(label = names_to_display[.N()$ids]), size = 2, color = "black") +
  scale_edge_linetype_manual(values = c("1" = "solid", "5" = "dashed")) +
  guides(edge_linetype = "none") +
  theme_graph()
ggsave("f:/git/sslab/P2y12r-and-C1q/res/P2ry12/Cop1_Cebpb_path.tiff")
```


# number of DEGs in different orders  
```{r}
tg <- as_tbl_graph(all_path_df)

DEG_3_orders <- tg %>% 
  dplyr::mutate(dfsr = bfs_dist(root = .N()$name == "70839", mode = "out")) %>% as.data.frame()
  dplyr::filter(.N()$name %in% intersect(mapIds(org.Mm.eg.db, as.character(pvn_DEGs_A3), "ENTREZID", "SYMBOL"), 
                                  mapIds(org.Mm.eg.db, as.character(pvn_DEGs_L3), "ENTREZID", "SYMBOL"))) %>% 
  as_tibble() %>% 
  pull(dfsr) %>% 
  table() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames(c("order", "freq"))

DEG_14_orders <- tg %>% 
  dplyr::mutate(bfsr = bfs_dist(root = .N()$name == "70839", mode = "out")) %>% 
  dplyr::filter(.N()$name %in% intersect(mapIds(x = org.Mm.eg.db, keys = as.character(pvn_DEGs_A14), column = "ENTREZID", keytype = "SYMBOL"), 
                                         mapIds(x = org.Mm.eg.db, keys = as.character(pvn_DEGs_L14), column = "ENTREZID", keytype = "SYMBOL"))) %>% 
  as_tibble() %>% 
  pull(bfsr) %>% 
  table() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames(c("order", 'freq'))
```

```{r}
tg %>% 
  dplyr::mutate(bfsr = bfs_dist(root = .N()$name == "70839", mode = "out")) %>% 
  dplyr::filter(.N()$name %in% intersect(mapIds(x = org.Mm.eg.db, keys = as.character(pvn_DEGs_A14), column = "ENTREZID", keytype = "SYMBOL"), 
                                         mapIds(x = org.Mm.eg.db, keys = as.character(pvn_DEGs_L14), column = "ENTREZID", keytype = "SYMBOL"))) %>% 
  as_tibble() %>% 
  mutate(symbol = mapIds(org.Mm.eg.db, keys = .$name, keytype = "ENTREZID", column = "SYMBOL")) %>% 
  magrittr::set_colnames(c("entrez", "order", "symbol")) %>% 
  write.csv(file = "../res/P2ry12/A14_L14_genes_in_different_order.csv", row.names = F, quote = F)

tg %>% 
  dplyr::mutate(dfsr = bfs_dist(root = .N()$name == "70839", mode = "out")) %>% 
  dplyr::filter(.N()$name %in% intersect(mapIds(org.Mm.eg.db, as.character(pvn_DEGs_A3), "ENTREZID", "SYMBOL"), 
                                  mapIds(org.Mm.eg.db, as.character(pvn_DEGs_L3), "ENTREZID", "SYMBOL"))) %>% 
  as_tibble() %>% 
  mutate(symbol = mapIds(org.Mm.eg.db, keys = .$name, keytype = "ENTREZID", column = "SYMBOL")) %>% 
  magrittr::set_colnames(c("entrez", "order", "symbol")) %>% 
  write.csv(file = "../res/P2ry12/A3_L3_genes_in_different_order.csv", row.names = F, quote = F)
```


```{r}
DEG_3_orders$group = '3'
DEG_14_orders$group = '14'

DEG_3_orders %>% 
  rbind(DEG_14_orders) %>% 
  ggplot(aes(order, freq)) +
  geom_bar(stat = "identity", position = "dodge", aes(fill = group)) +
  scale_fill_brewer(name = NULL, type = "qual", palette = "Set1", direction = -1) +
  ggtitle(label = "Number of DEGs in different order")

ggsave(filename = "../res/P2ry12/Number-of-DEGs-in-different-order.tiff")
```


# migration
```{r}
p2ry12_downstream_genes <- c("Chac1", "Ltb4r1", "Mmp9", 
                             "Hdc", "Zfp607a", "Mthfd2", 
                             "Plat", "Fancg", "Pla2g4b", 
                             "Cebpb", "Vkorc1")
p2ry12_downstream_genes_entrez <- mapIds(org.Mm.eg.db, 
                                         keys = p2ry12_downstream_genes, 
                                         keytype = "SYMBOL", 
                                         column = "ENTREZID")

migration_genes <- c("Cd177", "Mmp9", "Lcn2", "Anxa1", "Enpp2")
migration_genes_entrez <- mapIds(x = org.Mm.eg.db, 
                                 keys = migration_genes, 
                                 keytype = "SYMBOL", 
                                 column = "ENTREZID")

migration_paths <- vector(mode = "list")

for(i in p2ry12_downstream_genes_entrez){
  x <- do.call(what = "shortest_paths", 
          args = list(
            graph = ig, 
            from = V(ig)$name == i, 
            to = V(ig)$name %in% migration_genes_entrez, 
            mode = "out", 
            output = "epath"
          ))
  x <- x$epath
  migration_paths <- append(migration_paths, values = x)
}


migration_path_df <- migration_paths %>% 
  sapply(as_ids) %>% 
  lapply(as.matrix) %>% 
  unlist() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames("from_to") %>% 
  separate(col = "from_to", into = c("from", "to"), sep = "\\|")

migration_path_KEGG <- left_join(migration_path_df, all_path_df, 
          by = c("from" = "from", "to" = "to"))

N <- tibble(
  ids = c(migration_path_KEGG$from, migration_path_KEGG$to) %>% unique()
) %>% 
  mutate(
    shape = ifelse(grepl("^cpd:|^gl:|^dr:", ids, ignore.case = F), "22", "21")
  )

E <- migration_path_KEGG

tg_migration <- tbl_graph(nodes = N, edges = E, directed = T)

set.seed(123)
tg_migration %>% 
  mutate(name = names_to_display[ids], 
         ncol = ifelse(ids %in% migration_genes_entrez, "tomato", 
                       ifelse(ids %in% p2ry12_downstream_genes_entrez, "blue", "gray"))) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == 30), 
                     label = subtype), 
                 start_cap = circle(1.5, "mm"),
                 end_cap = circle(3, "mm"), 
                 arrow = arrow(length = unit(2, "mm")), 
                 color = "gray40", 
                 angle_calc = "along", 
                 label_size = 1, 
                 label_dodge = unit(1, "mm")) +
  geom_edge_link(aes(filter = (angle == 90), 
                     label = subtype), 
                 start_cap = circle(1.5, "mm"), 
                 end_cap = circle(3, "mm"), 
                 arrow = arrow(length = unit(1.2, "mm"), angle = 90), 
                 color = "gray40", 
                 angle_calc = "along", 
                 label_size = 1, 
                 label_dodge = unit(1, "mm")) +
  geom_node_point(aes(shape = shape, col = ncol), size = 6, show.legend = F) +
  geom_node_text(aes(label = name), size = 2.5) +
  scale_color_identity()

ggsave("../res/P2ry12/migration-20210807.tiff")
```


# Calcium related pathway

```{r}
library(KEGGREST)
listDatabases()

mmu_pathways <- keggList(database = "pathway", organism = "mmu")
mmu_pathways %>% class()
grep("Calcium", mmu_pathways, ignore.case = T, value = T)

pvn3_common_down_genes_entrez <- mapIds(org.Mm.eg.db, 
                                        keys = pvn3_common_down_genes, 
                                        keytype = "SYMBOL", 
                                        column = "ENTREZID")

pvn3_common_up_genes_entrez <- mapIds(org.Mm.eg.db, 
                                      keys = pvn3_common_up_genes, 
                                      keytype = "SYMBOL", 
                                      column = "ENTREZID")
library(pathview)
pathview(gene.data = c(pvn3_common_down_genes_entrez, pvn3_common_up_genes_entrez) %>% unname() %>% unique() %>% na.omit() %>% as.character(), 
         pathway.id = c("04020", "04961"), 
         species = "mmu", 
         gene.idtype = "KEGG")
```


# Piezo1
```{r}
names_to_display[which(names_to_display == "Piezo1")]
```

```{r}
tg %>% 
  mutate(ids = name, 
         name = names_to_display[ids], 
         dist = bfs_dist(root = .N()$name == "Piezo1", mode = "out")) %>% 
  filter(.N()$name == "Piezo1")
```


```{r}
listDatabases()
keggLink("pathway", "br:234839")
keggLink("mmu:234839")
```

```{r}
pathview(gene.data = "234839", 
         pathway.id = "22128", 
         species = "ko")
```




