---
title: "CCRCC"
author: "yincy"
date: "5/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(Seurat)
library(magrittr)
library(data.table)
library(biomaRt)
library(SingleCellExperiment)
library(EnsDb.Hsapiens.v86)
library(tidyverse)
```


# reform ccrcc
```{r}
ccrcc <- readRDS("/home/yincy/git/Data/kidney/ccRCC/ccRCC_6pat_Seurat.rds")
```

```{r}
# rename ident
ccrcc <- RenameIdents(object = ccrcc, 
                      "0" = "CD8A+ Exhausted", 
                      "1" = "TAM HLAhi", 
                      "2" = "CD8A+ Tissue-resident", 
                      "3" = "CD4+ Naive", 
                      "4" = "CD8A+ NK-like", 
                      "5" = "CD14+/CD16+ Monocyte", 
                      "6" = "CD4+ Treg", 
                      "7" = "CD4+ Activated IEG", 
                      "8" = "Ambiguous", 
                      "9" = "CD45- PAX8+ renal epithelium", 
                      "10" = "Conventional NK", 
                      "11" = "CD45- Vascular Endothelium", 
                      "12" = "TAM HLAint", 
                      "13" = "cDC2", 
                      "14" = "CD14+ Monocyte", 
                      "15" = "CD8A+ Proliferating", 
                      "16" = "CD45- ccRCC CA9+", 
                      "17" = "NK HSP+", 
                      "18" = "TAM/TCR (Ambiguos)", 
                      "19" = "CD8A+ Exhausted IEG", 
                      "20" = "CD45- Myofibroblast", 
                      "21" = "Mast", 
                      "22" = "B cell", 
                      "23" = "Ambiguous", 
                      "24" = "Ambiguous", 
                      "25" = "Ambiguous", 
                      "26" = "Ambiguous", 
                      "27" = "TAM ISGhi", 
                      "28" = "Megakaryocyte", 
                      "29" = "Ambiguous/Dead", 
                      "30" = "TAM ISGint", 
                      "31" = "CD4+ Effector", 
                      "32" = "CD4+ Proliferating", 
                      "33" = "cDC1", 
                      "34" = "pDC")
levels(ccrcc)

# recode sample
ccrcc$Sample <- as.character(ccrcc$Sample)
ccrcc$Sample <- ifelse(ccrcc$Sample == "t1", "Nivo Exposed", 
                       ifelse(ccrcc$Sample == "t2", "Ipi/Nivo Resist",
                              ifelse(ccrcc$Sample == "t3", "Ipi/Nivo Mixed",
                                     ifelse(ccrcc$Sample == "t4", "Ipi/Nivo CR", ccrcc$Sample))))
ccrcc$Sample %>% unique()

# recode region
ccrcc_regions <- read.table("/home/yincy/git/Data/kidney/ccRCC/ccRCC_regions.txt", 
                            sep = "\t", 
                            header = T)

ccrcc$region <- ifelse(ccrcc$region == "SupraLateral", "Near",
                        ifelse(ccrcc$region == "LowerLateral", "Far",
                               ifelse(ccrcc$region == "LowerMedial", "Center",
                                      ifelse(ccrcc$region == "Medial", "Near",
                                             ifelse(ccrcc$region == "Lateral", "Far",
                                                    ifelse(ccrcc$region == "Upper", "Near",
                                                           ifelse(ccrcc$region == "Lower", "Far", ccrcc$region)))))))
ccrcc$region %>% unique()

saveRDS(object = ccrcc, 
        file = "/home/yincy/git/Data/kidney/ccRCC/ccRCC_6pat_Seurat.rds")
```


# cells in different regions
```{r, message=FALSE}
ccrcc <- readRDS("/home/yincy/git/Data/Kidney/ccRCC/ccRCC_6pat_Seurat.rds")

num_cells <- ccrcc[[]] %>% 
    filter(Sample %in% c('UT1', "UT2"), !grepl("^Ambiguous", cell_name)) %>% 
    group_by(region, type) %>% 
    summarise(n = n())

plot_data <- ccrcc[[]] %>% 
    filter(Sample %in% c('UT1', "UT2"), !grepl("^Ambiguous", cell_name)) %>% 
    select(region, type, Sample, Sample2, cell_name) %>% 
    arrange(Sample, cell_name) %>%
    mutate(cell = ifelse(grepl("^CD14+", cell_name), "CD14+", 
                         ifelse(grepl("CD45- ccRCC CA9+", cell_name), "ccRCC CA9+", 
                                ifelse(grepl("CD45- Myofibroblast", cell_name), "Myofibroblast", 
                                       ifelse(grepl("CD45- PAX8+ renal epithelium", cell_name), "PAX8+ renal epithelium", 
                                              ifelse(grepl("CD45- Vascular Endothelium", cell_name), "Vascular Endothelium", 
                                                     ifelse(grepl("^CD8A+", cell_name), "CD8+", 
                                                            ifelse(grepl("DC", cell_name), "DC", 
                                                                   ifelse(grepl("NK", cell_name), "NK", 
                                                                          ifelse(grepl("^TAM", cell_name), "TAM", 
                                                                                 ifelse(grepl("CD4+", cell_name), "CD4+", cell_name))))))))))) %>% 
    select(region, type, Sample, cell, cell_name) %>% 
    group_by(region, type, cell) %>% 
    summarise(n = n()) %>% 
    mutate(prop = ifelse(type == "Tumor" & region == "Center", round(n / num_cells[1, 3, drop = T], 3), 
                         ifelse(type == "Tumor" & region == "Far", round(n / num_cells[2, 3, drop = T], 3), 
                                ifelse(type == "Tumor" & region == "Near", round(n / num_cells[3, 3, drop = T], 3), 
                                       ifelse(type == "Normal" & region == "Normal", round(n / num_cells[4, 3, drop = T], 3), NA)))), 
           region = factor(region, levels = c("Normal", "Near", "Center", "Far", "PBMC", "LymphNode")))

plot_data %>% 
    ggplot(aes(reorder(cell, prop), region)) +
    geom_point(aes(size = prop), show.legend = T) +
    scale_x_discrete(name = NULL) +
    scale_y_discrete(name = NULL) +
    scale_size_continuous(breaks = seq(-1, 10, 2)) +
    ggtitle(label = "proprotion of different cells in different regions") +
    theme(axis.text.x = element_text(angle = -70, hjust = 0, vjust = 0.5, size = 8), 
          panel.background = element_rect(fill = NA, color = "black", size = 0.5, linetype = 1), 
          panel.grid.major = element_line(color = "grey70", size = 0.2, linetype = 2), 
          axis.line = element_line(color = "grey20", lineend = "round"), 
          plot.title = element_text(hjust = 0.5))

ggsave("/home/yincy/git/Data/Kidney/ccRCC/res/cells_in_different_regions_ccrcc.tiff", 
       width = 10, height = 6.18)
```


# prepare data for cell-cell communication
## tumor tissue
```{r}
ccrcc_UT_tumor <- subset(ccrcc, subset = Sample %in% c("UT1", "UT2") & type == "Tumor" & cell_name != "Ambiguous" & cell_name != "Ambiguous/Dead")
```

```{r}
# cell_meta_tumor <- ccrcc_UT_tumor[[]] %>% 
#     select(cell, cell_name)
# 
# write.table(x = cell_meta_tumor, 
#             file = "/home/yincy/git/Data/kidney/ccRCC/res/cell_meta_tumor.txt", 
#             sep = "\t", 
#             row.names = F, 
#             quote = F)
```

```{r}
# counts_data_tumor <- GetAssayData(ccrcc_UT_tumor, slot = "data") %>% 
#     as.matrix() %>% 
#     round(digits = 3) %>% 
#     as.data.frame() %>% 
#     rownames_to_column("ensembl")
# 
# norm_data[1:10, 1:5]
# 
# fwrite(counts_data_tumor, 
#        "/home/yincy/git/Data/kidney/ccRCC/res/norm_data_tumor.txt", 
#        row.names = F, 
#        quote = F, 
#        sep = "\t")
```

## noram tissue
```{r}
ccrcc_UT_norm <- subset(ccrcc, subset = Sample %in% c("UT1", "UT2") & type == "Normal" & cell_name != "Ambiguous" & cell_name != "Ambiguous/Dead")
```

```{r}
# cell_meta_norm <- ccrcc_UT_norm[[]] %>% 
#     select(cell, cell_name)
# 
# write.table(cell_meta_norm, 
#             "/home/yincy/git/Data/kidney/ccRCC/res/cell_meta_normal.txt", 
#             row.names = F, 
#             quote = F, 
#             sep = "\t")
```

```{r}
# counts_data_norm <- GetAssayData(ccrcc_UT_norm, "data") %>% 
#     as.matrix() %>% 
#     round(digits = 3) %>% 
#     as.data.frame() %>% 
#     rownames_to_column("ensembl")
# 
# counts_data_norm[1:10, 1:5]
# 
# fwrite(counts_data_norm, 
#        "/home/yincy/git/Data/kidney/ccRCC/res/norm_data_normal.txt", 
#        sep = "\t", 
#        row.names = F, 
#        quote = F)
```

# expression of Pdgf
```{r, message=FALSE}
hgs <- genes(EnsDb.Hsapiens.v86)
Pdgf <- hgs$symbol[grepl("^PDGF", hgs$symbol, ignore.case = F)] %>% unique() %>% sort()
Pdgf_ensembl <- mapIds(EnsDb.Hsapiens.v86, 
                  keys = Pdgf, 
                  keytype = "SYMBOL", 
                  column = "GENEID")

plots_tumor <- VlnPlot(object = ccrcc_UT_tumor, 
        features = Pdgf_ensembl, 
        group.by = "cell_name", 
        combine = F)

plot_grid(plotlist = plots_tumor, 
          ncol = 2) 

for(i in seq_along(plots)){
    plots[[i]] +
        scale_x_discrete(name = NULL) +
        scale_y_continuous(name = "relative expression") +
        theme(legend.position = "none", 
              axis.text.x = element_text(size = 6), 
              axis.ticks.length.y = unit(0.1, units = "cm")) +
        ggtitle(names(Pdgf_ensembl)[[i]] %>% stringr::str_to_title())
    
    ggsave(filename = paste("/home/yincy/git/Data/kidney/ccRCC/res/", names(Pdgf_ensembl)[[i]], "_tumor", ".tiff", sep = ""), 
           width = 10, height = 6.18)
}
```

```{r}
plots_norm <- VlnPlot(object = ccrcc_UT_norm, 
                      features = Pdgf_ensembl, 
                      group.by = "cell_name", 
                      combine = F)

plot_grid(plotlist = plots_norm, 
          ncol = 2)

for(i in seq_along(plots_norm)){
    plots_norm[[i]] +
        scale_x_discrete(name = NULL) +
        scale_y_continuous(name = "relative expression") +
        theme(legend.position = "none", 
              axis.text.x = element_text(size = 6), 
              axis.ticks.length.y = unit(0.1, units = "cm")) +
        ggtitle(names(Pdgf_ensembl)[[i]] %>% stringr::str_to_title())
    
    ggsave(filename = paste("/home/yincy/git/Data/kidney/ccRCC/res/", names(Pdgf_ensembl)[[i]], "_norm", ".tiff", sep = ""), 
           width = 10, height = 6.18)
}
```


# process CC
## tumor tissue
```{r}
all_means <- read.table("/home/yincy/git/Data/Kidney/ccRCC/res/ccrcc-tumor-tissue/means.txt", 
                        sep = "\t", 
                        header = T, 
                        check.names = F)
all_pvalue <- read.table("/home/yincy/git/Data/Kidney/ccRCC/res/ccrcc-tumor-tissue/pvalues.txt", 
                         sep = "\t", 
                         header = T, 
                         check.names = F)

cols_to_remove <- c("id_cp_interaction", "partner_a", 
                    "partner_b", "gene_a", "gene_b", 
                    "secreted", "receptor_a", "receptor_b", 
                    "annotation_strategy", "is_integrin")

all_pvalue_long <- all_pvalue %>% 
    select(-cols_to_remove) %>% 
    gather(key = "cellA|cellB", value = "pvalue", -interacting_pair)

all_means_long <- all_means %>% 
    select(-cols_to_remove) %>% 
    gather(key = "cellA|cellB", value = "means", -interacting_pair)

all_pvalue_means_long <- left_join(all_pvalue_long, all_means_long, 
                                   by = c("interacting_pair" = "interacting_pair", "cellA|cellB" = "cellA|cellB"))
```


```{r}
all_pvalue_means_long %>% 
    filter(!grepl("Ambiguos", `cellA|cellB`)) %>% 
    filter(str_detect(`cellA|cellB`, "(^TAM ([:alnum:]){1,}\\|CD45- Myofibroblast)|(CD45- Myofibroblast\\|TAM ([:alnum:]){1,})")) %>% 
    ggplot(aes(`cellA|cellB`, interacting_pair)) +
    geom_point(aes(size = means, color = pvalue)) +
    scale_color_gradientn(colours = colorRampPalette(c("red", "yellow", "blue", "black"), alpha=TRUE)(n=256)) +
    scale_x_discrete(name = NULL) +
    scale_y_discrete(name = "interaction pairs") +
    scale_size_area(max_size = 4) +
    theme(axis.ticks.y = element_line(size = 0.1), 
          axis.text.y = element_text(size = 5), 
          axis.text.x = element_text(angle = -50, hjust = 0, size = 7))


ggsave("/home/yincy/git/Data/Kidney/ccRCC/res/ccrcc-tumor-tissue/TAM-fibroblast-interaction-tumor.pdf", 
       width = 5, 
       height = 120, 
       limitsize = F, 
       device = cairo_pdf)
```


## normal tissue
```{r}
all_means <- read.table("/home/yincy/git/Data/Kidney/ccRCC/res/ccrcc-noram-tissue/means.txt", 
                        sep = "\t", 
                        header = T, 
                        check.names = F)
all_pvalue <- read.table("/home/yincy/git/Data/Kidney/ccRCC/res/ccrcc-noram-tissue/pvalues.txt", 
                         sep = "\t", 
                         header = T, 
                         check.names = F)

cols_to_remove <- c("id_cp_interaction", "partner_a", 
                    "partner_b", "gene_a", "gene_b", 
                    "secreted", "receptor_a", "receptor_b", 
                    "annotation_strategy", "is_integrin")

all_pvalue_long <- all_pvalue %>% 
    select(-cols_to_remove) %>% 
    gather(key = "cellA|cellB", value = "pvalue", -interacting_pair)

all_means_long <- all_means %>% 
    select(-cols_to_remove) %>% 
    gather(key = "cellA|cellB", value = "means", -interacting_pair)

all_pvalue_means_long <- left_join(all_pvalue_long, all_means_long, 
                                   by = c("interacting_pair" = "interacting_pair", "cellA|cellB" = "cellA|cellB"))
```

```{r}
all_pvalue_means_long %>% 
    filter(!grepl("Ambiguos", `cellA|cellB`)) %>% 
    filter(str_detect(`cellA|cellB`, "(^TAM ([:alnum:]){1,}\\|CD45- Myofibroblast)|(CD45- Myofibroblast\\|TAM ([:alnum:]){1,})")) %>% 
    ggplot(aes(`cellA|cellB`, interacting_pair)) +
    geom_point(aes(size = means, color = pvalue)) +
    scale_color_gradientn(colours = colorRampPalette(c("red", "yellow", "blue", "black"), alpha=TRUE)(n=256)) +
    scale_x_discrete(name = NULL) +
    scale_y_discrete(name = "interaction pairs") +
    scale_size_area(max_size = 4) +
    theme(axis.ticks.y = element_line(size = 0.1), 
          axis.text.y = element_text(size = 5), 
          axis.text.x = element_text(angle = -50, hjust = 0, size = 7))


ggsave("/home/yincy/git/Data/Kidney/ccRCC/res/ccrcc-noram-tissue/TAM-fibroblast-interaction-normal.pdf", 
       width = 5, 
       height = 120, 
       limitsize = F, 
       device = cairo_pdf)
```



