---
title: "live-image"
author: "YinCY"
date: "7/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```

# 20210204
```{r}
li_20210204 <- read.csv("G:/data/live-image/20210204/210204 - stat.csv")
```

```{r}
set.seed(117)
li_20210204 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.),
         se = sd/sqrt(3-1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.4) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), size = 2, width = 0.1) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  theme_classic() +
  ggtitle("PB3")

ggsave("G:/data/live-image/20210204/20210204-live-image.tiff", 
       width = 7, height = 7)
```


# 20210222
```{r}
li_20210222 <- read.csv("G:/data/live-image/20210222/20210222 - stat.csv")
```

```{r}
li_20210222 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.), 
         se = sd/sqrt(3-1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.4) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), size = 2, width = 0.1) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  theme_classic() +
  ggtitle("PB3")

ggsave("G:/data/live-image/20210222/20210222-live-image.tiff", 
       width = 7, height = 7)
```


# 20210531
```{r}
li_20210531_KP_B6 <- read.csv("G:/data/live-image/20210531/20210531-KP-B6/20210531-KP-B6-stat.csv")
li_20210531_PB3 <- read.csv("G:/data/live-image/20210531/20210531-PB3/20210531 - PB3 - stat.csv")
```

```{r}
p1 <- li_20210531_KP_B6 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm2.sr.), 
         sd = sd(Avg.Radiance..p.s.cm2.sr.), 
         se = ifelse(group == "TAM", sd/sqrt(4-1), sd/sqrt(3-1))) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", position = "dodge", width = 0.4) +
  geom_errorbar(aes(x = group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm2.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  ggtitle(label = "KP-B6")

p2 <- li_20210531_PB3 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.), 
         se = ifelse(group == "TAM", sd/sqrt(5-1), sd/sqrt(6-1))) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  ggtitle("PB3")
```

```{r}
library(patchwork)

p1 + p2

ggsave("G:/data/live-image/20210531/20210531-live-image.tiff")
```


# 20210702
```{r}
li_20210702 <- read.csv("G:/data/live-image/20210702/20210702-PB3-stat.csv")

li_20210702 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm2.sr.), 
         sd = sd(Avg.Radiance..p.s.cm2.sr.), 
         se = sd/sqrt(2-1)) %>% 
  ggplot()+
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm2.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  ggtitle("PB3")

ggsave("G:/data/live-image/20210702/20210702-live-image.tiff", 
       width = 7, height = 7)
```

# 20210815
```{r}
pb3_wt <- read.csv("G:/data/live-image/20210815/20210815-PB3-stat.csv")
pb3_wt %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm2.sr.), 
         sd = sd(Avg.Radiance..p.s.cm2.sr.), 
         se = sd / sqrt(4 - 1)) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm2.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  labs(title = "PB3")

ggsave("G:/data/live-image/20210815/20210815-live-image.tiff", 
       width = 7, height = 7)
```

# 20220117
```{r}
pb2 <- read.csv("G:/data/live-image/20220117/stat-20220117.csv")
```

```{r}
pb2 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.), 
         se = sd / sqrt(4 - 1)) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL, labels = c("Capsaicin (n = 4)", "Control (n = 3)")) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  labs(title = "PB2") +
  theme(axis.text.x = element_text(size = 15), 
        axis.title.y = element_text(size = 10))

ggsave("G:/data/live-image/20220117/20220117-PB2.tiff")
```

# 20220124
```{r}
pb2 <- read.csv("G:/data/live-image/20220124/stat-20220124.csv")
```

```{r}
pb2 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.), 
         se = sd / sqrt(4 - 1)) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL, labels = c("Capsaicin (n = 4)", "Control (n = 3)")) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  labs(title = "PB2") +
  theme(axis.text.x = element_text(size = 15), 
        axis.title.y = element_text(size = 10))

ggsave("G:/data/live-image/20220124/20220124-pb2.tiff")
```

# PB3 flod change
```{r}
library(tidyverse)
pooled <- readxl::read_xlsx("G:/data/live-image/PB3-tumor.xlsx", sheet = 3)
```

```{r}
pooled %>% 
  group_by(group) %>% 
  mutate(mean = mean(flod_change), 
         sd = sd(flod_change), 
         se = sd / sqrt(10-1)) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, flod_change), width = 0.1) +
  geom_segment(aes(x = "Corn Oil", y = 35, xend = "Tamoxifen", yend = 35), 
               colour = "black", linetype = 1, size = 0.7) +
  geom_text(aes(x = 1.5, y = 37, label = "p < 0.01")) +
  scale_y_continuous(name = "flod change", limits = c(0, 40)) +
  scale_x_discrete(name = NULL) +
  theme_classic()

ggsave("G:/data/live-image/PB3-Pdgfb.png")
```


# CCK8
```{r}
cck8 <- readxl::read_xlsx("G:/data/kidney/Tumor/CCK8/20220304-Pdgfr-inhibitor-cck8.xlsx", 
                          col_types = c("text", "text", "numeric"))
```

```{r}
ggplot(cck8, aes(Treatment, OD450, group = Time)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~Time) +
  scale_x_discrete(name = NULL) +
  scale_fill_brewer(name = NULL, type = "qual") +
  theme(axis.text.x = element_text(size = 7))

ggsave("G:/data/kidney/Tumor/CCK8/20220304-Pdgfr-inhibitor-cck8.tiff", width = 10)
```



