---
title: "Lung"
author: "yincy"
date: "5/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# loading packages
```{r, message=FALSE}
library(SingleCellExperiment)
library(scran)
library(scater)
library(tidyverse)
```


# construct SingleCellExperiment object
```{r}
load("/home/yincy/git/Data/Lung/GSE130148/GSE130148_raw_counts.RData")
cell_meta <- read.table("/home/yincy/git/Data/Lung/GSE130148/GSE130148_barcodes_cell_types.txt", 
                        sep = "\t", 
                        header = T)
rownames(cell_meta) <- cell_meta$cell.barcode

genes <- data.frame(symbol = rownames(raw_counts))
rownames(genes) <- genes$symbol

sce.lung <- SingleCellExperiment(assays = list(counts = raw_counts), 
                                 rowData = genes, 
                                 colData = cell_meta)

sce.lung <- computeSumFactors(sce.lung, clusters = sce.lung$celltype)
sce.lung <- logNormCounts(sce.lung)
```


# expression of Pdgf
```{r}
Pdgf <- grep("^PDGF", rownames(sce.lung), ignore.case = F, value = T) %>% sort()

plotExpression(sce.lung, 
               features = Pdgf, 
               x = "celltype", 
               colour_by = "celltype", 
               point_size = 0.5, 
               jitter_type = "jitter", 
               show_violin = T) +
    theme(axis.text.x = element_text(angle = -55, hjust = 0), 
          legend.position = "none") +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = "relative expression")


ggsave("/home/yincy/git/Data/Lung/GSE130148/res/lung_cancer_Pdgf.tiff", 
       width = 10, height = 6.18, limitsize = F)
```


