---
title: "live-image"
author: "YinCY"
date: "7/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```

# live image data
## 20210204
```{r}
li_20210204 <- read.csv("G:/data/live-image/20210204/210204 - stat.csv")
```

```{r}
set.seed(117)
li_20210204 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.),
         se = sd/sqrt(3-1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.4) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), size = 2, width = 0.1) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  theme_classic() +
  ggtitle("PB3")

ggsave("G:/data/live-image/20210204/20210204-live-image.tiff", 
       width = 7, height = 7)
```


## 20210222
```{r}
li_20210222 <- read.csv("G:/data/live-image/20210222/20210222 - stat.csv")
```

```{r}
li_20210222 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.), 
         se = sd/sqrt(3-1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.4) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), size = 2, width = 0.1) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  theme_classic() +
  ggtitle("PB3")

ggsave("G:/data/live-image/20210222/20210222-live-image.tiff", 
       width = 7, height = 7)
```


## 20210531
```{r}
li_20210531_KP_B6 <- read.csv("G:/data/live-image/20210531/20210531-KP-B6/20210531-KP-B6-stat.csv")
li_20210531_PB3 <- read.csv("G:/data/live-image/20210531/20210531-PB3/20210531 - PB3 - stat.csv")
```

```{r}
p1 <- li_20210531_KP_B6 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm2.sr.), 
         sd = sd(Avg.Radiance..p.s.cm2.sr.), 
         se = ifelse(group == "TAM", sd/sqrt(4-1), sd/sqrt(3-1))) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", position = "dodge", width = 0.4) +
  geom_errorbar(aes(x = group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm2.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  ggtitle(label = "KP-B6")

p2 <- li_20210531_PB3 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.), 
         se = ifelse(group == "TAM", sd/sqrt(5-1), sd/sqrt(6-1))) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  ggtitle("PB3")
```

```{r}
library(patchwork)

p1 + p2

ggsave("G:/data/live-image/20210531/20210531-live-image.tiff")
```


## 20210702
```{r}
li_20210702 <- read.csv("G:/data/live-image/20210702/20210702-PB3-stat.csv")

li_20210702 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm2.sr.), 
         sd = sd(Avg.Radiance..p.s.cm2.sr.), 
         se = sd/sqrt(2-1)) %>% 
  ggplot()+
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm2.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  ggtitle("PB3")

ggsave("G:/data/live-image/20210702/20210702-live-image.tiff", 
       width = 7, height = 7)
```

## 20210815
```{r}
pb3_wt <- read.csv("G:/data/live-image/20210815/20210815-PB3-stat.csv")
pb3_wt %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm2.sr.), 
         sd = sd(Avg.Radiance..p.s.cm2.sr.), 
         se = sd / sqrt(4 - 1)) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm2.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  labs(title = "PB3")

ggsave("G:/data/live-image/20210815/20210815-live-image.tiff", 
       width = 7, height = 7)
```

## PB3 flod change
```{r}
library(tidyverse)
pooled <- readxl::read_xlsx("G:/data/live-image/PB3-tumor.xlsx", sheet = 3)
```

```{r}
pooled %>% 
  group_by(group) %>% 
  mutate(mean = mean(flod_change), 
         sd = sd(flod_change), 
         se = sd / sqrt(10-1)) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, flod_change), width = 0.1) +
  geom_segment(aes(x = "Corn Oil", y = 35, xend = "Tamoxifen", yend = 35), 
               colour = "black", linetype = 1, size = 0.7) +
  geom_text(aes(x = 1.5, y = 37, label = "p < 0.01")) +
  scale_y_continuous(name = "flod change", limits = c(0, 40)) +
  scale_x_discrete(name = NULL) +
  theme_classic()

ggsave("G:/data/live-image/PB3-Pdgfb.png")
```


## 20220117
tumor sensory nerve
```{r}
pb2 <- read.csv("G:/data/live-image/20220117/stat-20220117.csv")
```

```{r}
pb2 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.), 
         se = sd / sqrt(4 - 1)) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL, labels = c("Capsaicin (n = 4)", "Control (n = 3)")) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  labs(title = "PB2") +
  theme(axis.text.x = element_text(size = 15), 
        axis.title.y = element_text(size = 10))

ggsave("G:/data/live-image/20220117/20220117-PB2.tiff")
```

## 20220124
tumor sensory nerve
```{r}
pb2 <- read.csv("G:/data/live-image/20220124/stat-20220124.csv")
```

```{r}
pb2 %>% 
  group_by(group) %>% 
  mutate(mean = mean(Avg.Radiance..p.s.cm.sr.), 
         sd = sd(Avg.Radiance..p.s.cm.sr.), 
         se = sd / sqrt(4 - 1)) %>% 
  ggplot() +
  geom_bar(aes(group, mean), stat = "identity", width = 0.4, position = "dodge") +
  geom_errorbar(aes(group, ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_jitter(aes(group, Avg.Radiance..p.s.cm.sr.), width = 0.1, size = 2) +
  theme_classic() +
  scale_x_discrete(name = NULL, labels = c("Capsaicin (n = 4)", "Control (n = 3)")) +
  scale_y_continuous(name = expression(paste("Avg Radiance ", (photons/sec/cm^2/sr)))) +
  labs(title = "PB2") +
  theme(axis.text.x = element_text(size = 15), 
        axis.title.y = element_text(size = 10))

ggsave("G:/data/live-image/20220124/20220124-pb2.tiff")
```


# PB3 Pdgfr inhibitor in vitro assay
## CCK8 20220304
```{r}
cck8_0304 <- readxl::read_xlsx("G:/data/kidney/Tumor/CCK8/20220304-cck8-pdgfr-inhibitor-1h.xlsx", 
                          sheet = "Sheet1")

p1 <- cck8_0304 %>% group_by(group) %>% 
  mutate(mean = mean(OD450),
         n = n(),
         se = sd(OD450) / sqrt(n -1)) %>% 
  mutate(group = factor(group, levels = c("Control", 
                                          "1.0uM Pdgfr inhibitor", 
                                          "5.0uM Pdgfra inhibitor", 
                                          "10.0uM Pdgfrb inhibitor"))) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.6) +
  geom_jitter(aes(group, OD450),width = 0.2) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "OD450") +
  theme_classic() +
  theme(axis.text.x = element_text(hjust = 0.5, size = 8)) +
  labs(title = "growth inhibitory effects of Pdgfr inhibitors on PB3")

ggsave("G:/data/kidney/Tumor/CCK8/20220304-Pdgfr-inhibitor-cck8.tiff", width = 10)
```


## CCK8 20220311
```{r, warning=F}
# 3h after CCK8 addition
cck8_0311 <- readxl::read_xlsx("G:/data/kidney/Tumor/CCK8/20220311.xlsx", 
                               sheet = "Sheet1", 
                               col_types = c("text", "numeric"))
cck8_0311 %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(OD450, na.rm = T),
         se = sd(OD450, na.rm = T)/sqrt(n- 1), 
         group = factor(group, levels = c("Control", 
                                          "0.1uM Pdgfr inhibitor", 
                                          "1uM Pdgfr inhibitor", 
                                          "1uM Pdgfra inhibitor", 
                                          "10uM Pdgfra inhibitor", 
                                          "0.5uM Pdgfrb inhibitor", 
                                          "5uM Pdgfrb inhibitor"))) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.9) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(group, OD450), width = 0.2) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "OD450") +
  theme(axis.text.x = element_text(hjust = 0, size = 9, angle = -50))
```


## CCK8 20220404
```{r}
# 1h after CCK8 addition
cck8_0404 <- readxl::read_xlsx("G:/data/kidney/Tumor/CCK8/20220404-PB3-Pdgfr-inhibitor-CCK8-450.xlsx", 
                               sheet = "Sheet1")

p2 <- cck8_0404 %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(OD450), 
         se = sd(OD450) / sqrt(n - 1), 
         group = factor(group, levels = c("Control", 
                                          "0.1uM Pdgfr inhibitor", 
                                          "1.0uM Pdgfr inhibitor", 
                                          "0.5uM Pdgfra inhibitor", 
                                          "5.0uM Pdgfra inhibitor", 
                                          "1.0uM Pdgfrb inhibitor", 
                                          "10.0uM Pdgfrb inhibitor"))) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_jitter(aes(group, OD450), width = 0.2) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "OD450") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = -70, vjust = 0, hjust = 0, size = 8)) +
  labs(title = "growth inhibitory effects of Pdgfr inhibitors on PB3")

ggsave("G:/data/kidney/Tumor/CCK8/20220404-pdgfr-inhibitor-cck8.tiff", width = 10)
```


## CCK8 20220408
```{r}
cck8_0408 <- readxl::read_xlsx("G:/data/kidney/Tumor/CCK8/20220408-pb3-cck8.xlsx", 
                               sheet = "Sheet1")

cck8_0408 %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(OD450), 
         se = sd(OD450)/sqrt(n - 1), 
         group = factor(group, levels = c("Control", 
                                          "0.1uM Pdgfr inhibitor", 
                                          "1.0uM Pdgfr inhibitor", 
                                          "0.5uM Pdgfra inhibitor", 
                                          "5.0uM Pdgfra inhibitor", 
                                          "1.0uM Pdgfrb inhibitor", 
                                          "10.0uM Pdgfrb inhibitor"))) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se, width = 0.2)) +
  geom_jitter(aes(group, OD450), width = 0.2) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "OD450") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = -50, hjust = 0, size = 8)) +
  labs(title = "growth inhibitory effects of Pdgfr inhibitors on PB3") 

ggsave("G:/data/kidney/Tumor/CCK8/20220408-Pdgfr-inhibitor-cck8.tiff", width = 10, height = 7)
```



# fluoresence microscope
## a-SMA profile plot
```{r}
library(tidyverse)

# Corn Oil
pb3_corn_oil1 <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-corn-oil/a-SMA/intensity-plot/PB3-Corn-Oil-a-SMA-intensity-boundary-300-1.csv")
colnames(pb3_corn_oil1) <- c("Distance", "Gray_Value")

pb3_corn_oil2 <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-corn-oil/a-SMA/intensity-plot/PB3-Corn-Oil-a-SMA-intensity-boundary-450-2.csv")
colnames(pb3_corn_oil2) <- c("Distance", "Gray_Value")

pb3_corn_oil3 <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-corn-oil/a-SMA/intensity-plot/PB3-Corn-Oil-a-SMA-intensity-boundary-440-3.csv")
colnames(pb3_corn_oil3) <- c("Distance", "Gray_Value")

# boundary alignment
pb3_corn_oil1_normal_gray_value <- pb3_corn_oil1 %>% 
  filter(Distance < 300) %>% 
  summarise(mean = mean(Gray_Value)) %>% 
  magrittr::extract2(1)
pb3_corn_oil1_normalized <- pb3_corn_oil1 %>% 
  filter(Distance > 110) %>% 
  mutate(Distance = Distance - 110,
         Gray_Value_normalized = round(Gray_Value / pb3_corn_oil1_normal_gray_value, 3))
pb3_corn_oil1_normalized$file <- factor("Corn Oil 1")



pb3_corn_oil2_normal_gray_values <- pb3_corn_oil2 %>% 
  filter(Distance < 450) %>% 
  summarise(mean = mean(Gray_Value)) %>% 
  magrittr::extract2(1)
pb3_corn_oil2_normalized <- pb3_corn_oil2 %>% 
  filter(Distance > 260) %>% 
  mutate(Distance = Distance - 260, 
         Gray_Value_normalized = round(Gray_Value / pb3_corn_oil2_normal_gray_values, 3))
pb3_corn_oil2_normalized$file <- factor("Corn Oil 2")



pb3_corn_oil3_normal_gray_values <- pb3_corn_oil3 %>% 
  filter(Distance < 440) %>% 
  summarise(mean = mean(Gray_Value)) %>% 
  magrittr::extract2(1)

pb3_corn_oil3_normalized <- pb3_corn_oil3 %>% 
  filter(Distance > 250) %>% 
  mutate(Distance = Distance - 250, 
         Gray_Value_normalized = round(Gray_Value / pb3_corn_oil3_normal_gray_values, 3)) 
pb3_corn_oil3_normalized$file <- factor("Corn Oil 3")

pb3_corn_oil <- rbind(pb3_corn_oil1_normalized, 
                      pb3_corn_oil2_normalized, 
                      pb3_corn_oil3_normalized)


# Tamoxifen
pb3_tam1 <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-TAM/a-SMA/intensity-plot/PB3-TAM-a-SMA-intensity-plot-boundary-190-1.csv")
colnames(pb3_tam1) <- c("Distance", "Gray_Value")

pb3_tam2 <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-TAM/a-SMA/intensity-plot/PB3-TAM-a-SMA-intensity-plot-boundary-550-2.csv")
colnames(pb3_tam2) <- c("Distance", "Gray_Value")

pb3_tam3 <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-TAM/a-SMA/intensity-plot/PB3-TAM-a-SMA-intensity-plot-boundary-280-3.csv")
colnames(pb3_tam3) <- c("Distance", "Gray_Value")

# boundary alignment
pb3_tam1_normal_gray_value <- pb3_tam1 %>% 
  filter(Distance < 190) %>% 
  summarise(mean = mean(Gray_Value)) %>% 
  magrittr::extract2(1)
pb3_tam1_normalized <- pb3_tam1 %>% 
  mutate(Gray_Value_normalized = round(Gray_Value / pb3_tam1_normal_gray_value, 3))
pb3_tam1_normalized$file <- factor("Tamoxifen 1")

pb3_tam2_normal_gray_value <- pb3_tam2 %>% filter(Distance < 550) %>% 
  summarise(mean = mean(Gray_Value)) %>% 
  magrittr::extract2(1)
pb3_tam2_normalized <- pb3_tam2 %>% 
  filter(Distance > 350) %>% 
  mutate(Distance = Distance - 350,
    Gray_Value_normalized = round(Gray_Value / pb3_tam2_normal_gray_value, 3))
pb3_tam2_normalized$file <- factor("Tamoxifen 2")


pb3_tam3_normal_gray_value <- pb3_tam3 %>% 
  filter(Distance < 280) %>% 
  summarise(mean = mean(Gray_Value)) %>% 
  magrittr::extract2(1)
pb3_tam3_normalized <- pb3_tam3 %>% 
  filter(Distance > 280) %>% 
  mutate(Distance = Distance - 280, 
         Gray_Value_normalized = round(Gray_Value / pb3_tam3_normal_gray_value, 3))
pb3_tam3_normalized$file <- factor("Tamoxifen 3")

pb3_tam <- rbind(pb3_tam1_normalized, 
                 pb3_tam2_normalized,
                 pb3_tam3_normalized)

asma <- rbind(pb3_corn_oil, pb3_tam) 

library(stringr)
len <- str_count(asma$file, "[:alpha:]")
asma$group <- substr(asma$file, 1, len) %>% as.factor()
asma %>% head
asma %>% tail

aov(Gray_Value_normalized ~ Distance * group, data = asma) %>% summary
```


```{r}
asma %>% 
  ggplot(aes(Distance, Gray_Value_normalized)) +
  geom_line(aes(group = file, color = file)) +
  geom_vline(xintercept = 200, linetype = 2, size = 2, color = "gray40") +
  geom_segment(aes(x = max(Distance) * 1.01, 
                   y = 0.2, 
                   xend = max(Distance) * 1.01, 
                   yend = 1.3), 
               size = 1) +
  geom_text(aes(x = max(Distance) * 1.04, y = 0.75), angle = 90, label = "***") +
  theme_classic() +
  scale_color_brewer(name = NULL, type = "div", palette = 3) +
  scale_x_continuous(name = "Distance (um)") +
  scale_y_continuous(name = "normalized fluorsence intensity") +
  labs(title = "normalized fluoresence intensity of a-SMA")

# dir.create("G:/data/kidney/Tumor/PB3/res-microscope")
ggsave("G:/data/kidney/Tumor/PB3/res-microscope/a-SMA-intensity-plot.tiff", width = 10)
```


## a-SMA positive area
```{r}
pb3_corn_oil_asma <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-corn-oil/a-SMA/subregions/percent-area-PB3-Corn-Oil-a-SMA.csv")
pb3_corn_oil_asma$group = "Corn Oil"
pb3_tam_asma <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-TAM/a-SMA/subregions/percent-area-PB3-TAM-a-SMA.csv")
pb3_tam_asma$group = "Tamoxifen"

aov(percent_Area ~ group, data = rbind(pb3_corn_oil_asma, pb3_tam_asma)) %>% summary()
t.test(pb3_corn_oil_asma$percent_Area, pb3_tam_asma$percent_Area)

rbind(pb3_corn_oil_asma, pb3_tam_asma) %>% 
  ggplot(aes(group, percent_Area)) +
  geom_boxplot() +
  geom_jitter(size = 2, width = 0.1) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "percentage of a-SMA positve area", 
                     breaks = seq(10, 30, 10), 
                     labels = paste(seq(10, 30, 10), "%", sep = "")) +
  theme_classic()

ggsave("G:/data/kidney/Tumor/PB3/res-microscope/a-SMA-positive-area.tiff", width = 10)
```


## F480 positve area
```{r}
f480_corn_oil <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-corn-oil/F480/subregions/PB3-Corn-Oil-F480-area-percent.csv")
f480_corn_oil$group <- "Corn Oil"
f480_tam <- read.csv("G:/data/kidney/Tumor/PB3/kidney-PB3-TAM/F480/subregions/PB3-Corn-Oil-F480-area-percent.csv")
f480_tam$group <- "Tamoxifen"
```

```{r}
f480 <- rbind(f480_corn_oil, f480_tam)
aov(percent_Area ~ group, data = f480) %>% summary()
t.test(percent_Area ~ group, data = f480)

f480 %>% 
  ggplot(aes(group, percent_Area)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  geom_segment(x = 1, xend = 2, y = 50, yend = 50) +
  scale_y_continuous(name = "percentage of F4/80 \npositive area", 
                     limits = c(0, 55), 
                     breaks = seq(0, 50, 10), 
                     labels = paste(seq(0, 50, 10), "%", sep = "")) +
  scale_x_discrete(name = NULL) +
  geom_text(x = 1.5, y = 52, label = "p < 0.01") +
  theme_classic()
  

ggsave("G:/data/kidney/Tumor/PB3/res-microscope/F480-positve-area.tiff", width = 10)
```


## CD31 angiotool
```{r}
cd31_corn_normal <- readxl::read_xls("G:/data/kidney/Tumor/PB3/kidney-PB3-corn-oil/CD31/normal/prob-maps/PB3-Corn-Oil-normal-CD31-auto-diameter.xls")
cd31_corn_normal$group <- factor("Corn Oil")
cd31_corn_tumor <- readxl::read_xls("G:/data/kidney/Tumor/PB3/kidney-PB3-corn-oil/CD31/tumor/prob-maps/PB3-Corn-Oil-tumor-CD31-auto-diameter.xls")
cd31_corn_tumor$group <- factor("Corn Oil")

cd31_tam_normal <- readxl::read_xls("G:/data/kidney/Tumor/PB3/kidney-PB3-TAM/CD31/normal/prob-maps/PB3-TAM-normal-CD31-auto-diameter.xls")
cd31_tam_normal$group <- factor("Tamoxifen")
cd31_tam_tumor <- readxl::read_xls("G:/data/kidney/Tumor/PB3/kidney-PB3-TAM/CD31/tumor/prob-maps/PB3-TAM-tumor-CD31-auto-diameter.xls")
cd31_tam_tumor$group <- factor("Tamoxifen")
```


```{r}
library(ggplot2)
library(magrittr)
library(dplyr)
library(pipeR)
library(patchwork)

get_pval <- function(obj){
  obj[[1]][1, 5]
}

cd31_normal <- cd31_corn_normal %>% rbind(cd31_tam_normal) %>% 
  select(-c(2:11)) %>% 
  relocate(group, .after = 1)


aov(`Vessels percentage area` ~ group, data = cd31_normal) %>% summary()
p_normal_cd31_percentage <- cd31_normal %>% 
  select(group, `Vessels percentage area`) %>% 
  group_by(group) %>% 
  mutate(mean_percentage = mean(`Vessels percentage area`), 
         n = n(),
         se = sd(`Vessels percentage area`)/sqrt(n - 1)) %>% 
  ggplot(aes(group, mean_percentage)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean_percentage - se, ymax = mean_percentage + se), width = 0.2) +
  geom_jitter(aes(y = `Vessels percentage area`), width = 0.1) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "percentage of CD31 positive area", 
                     breaks = seq(5, 45, 10), 
                     labels = paste(seq(5, 45, 10), "%", sep = ""), 
                     limits = c(0, 40)) +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))


aov(`Junctions density` ~ group, data = cd31_normal) %>% summary()
p_normal_cd31_junction_density <- cd31_normal %>% 
  select(group, `Junctions density`) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(`Junctions density`), 
         se = sd(`Junctions density`)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = `Junctions density`), width = 0.1) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Junction density") +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))


aov(`Average Vessels Length` ~ group, data = cd31_normal) %>% summary()
p_normal_cd31_mean_length <- cd31_normal %>% 
  select(group, `Average Vessels Length`) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(`Average Vessels Length`), 
         se = sd(`Average Vessels Length`)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = `Average Vessels Length`), width = 0.1) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Average Vessel Length (um)",limits = c(0, 0.05)) +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))


aov(`Mean E Lacunarity` ~ group, data = cd31_normal) %>% summary()
p_normal_lacunarity <- cd31_normal %>% 
  select(group, `Mean E Lacunarity`) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(`Mean E Lacunarity`), 
         se = sd(`Mean E Lacunarity`) / sqrt(n - 1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = `Mean E Lacunarity`), width = 0.2) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Lacunarity") +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))


aov(`Explant area` ~ group, data = cd31_normal) %>% summary()
p_normal_end_point_density <- cd31_normal %>% 
  select(group, explant_area = `Explant area`, number_of_end_points = `Total Number of End Points`) %>% 
  mutate(end_points_density = round(number_of_end_points / explant_area, 4)) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(end_points_density), 
         se = sd(end_points_density) / sqrt(n - 1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = end_points_density), width = 0.2) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "end points density") +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))
```


```{r}
p_normal_cd31_percentage + 
  p_normal_cd31_mean_length + 
  p_normal_cd31_junction_density +
  # p_normal_end_point_density +
  p_normal_lacunarity +
  plot_annotation(title = "out side of tumor", 
                  theme = theme(plot.title = element_text(hjust = 0.5, size = 20)))
ggsave("G:/data/kidney/Tumor/PB3/res-microscope/PB3-CD31-normal.tiff", width = 10, height = 7)
```

```{r}
cd31_tumor <- rbind(cd31_corn_tumor, cd31_tam_tumor) %>% select(-c(2:11)) %>% relocate(group, .after = 1)

aov_tumor_cd31_percentage <- aov(`Vessels percentage area` ~ group, data = cd31_tumor) %>% summary 
p_tumor_cd31_percentage <- cd31_tumor %>% 
  select(group, `Vessels percentage area`) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(`Vessels percentage area`), 
         se = sd(`Vessels percentage area`)/sqrt(n - 1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = `Vessels percentage area`), width = 0.2) +
  geom_segment(aes(x = 1, 
                   y = max(cd31_tumor$`Vessels percentage area`) * 1.1, 
                   xend = 2, 
                   yend = max(cd31_tumor$`Vessels percentage area`) * 1.1), 
               size = 1.2) +
  geom_text(aes(x = 1.5, 
                y = max(cd31_tumor$`Vessels percentage area`) * 1.2), 
            label = round(get_pval(aov_tumor_cd31_percentage), 4)) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "percentage of CD31 positive area", 
                     breaks = seq(5, 30, 5), 
                     labels = paste(seq(5, 30, 5), "%", sep = ""), 
                     limits = c(0, 30)) +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))


aov_tumor_junctions_density <- aov(`Junctions density` ~ group, data = cd31_tumor) %>% summary
p_tumor_junction_density <- cd31_tumor %>% 
  select(`Image Name`, group, `Junctions density`) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(`Junctions density`), 
         se = sd(`Junctions density`)/sqrt(n - 1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = `Junctions density`), width = 0.2) +
  geom_segment(aes(x = 1, 
                   y = max(cd31_tumor$`Junctions density`) * 1.1), 
               xend = 2, 
               yend = max(cd31_tumor$`Junctions density`) * 1.1, 
               size = 1.2) + 
  geom_text(aes(x = 1.5, 
                y = max(cd31_tumor$`Junctions density`) * 1.2), 
            label = round(get_pval(aov_tumor_junctions_density), 4)) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "junctions density") +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))


aov_tumor_mean_vessels_length <- aov(`Average Vessels Length` ~ group, data = cd31_tumor) %>% summary
p_tumor_mean_vessels_length <- cd31_tumor %>% 
  select(group, average_vessels_length = `Average Vessels Length`) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(average_vessels_length), 
         se = sd(average_vessels_length)/sqrt(n - 1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = average_vessels_length), width = 0.2) +
  geom_segment(aes(x = 1, 
                   y = max(cd31_tumor$`Average Vessels Length`) * 1.1, 
                   xend = 2, 
                   yend = max(cd31_tumor$`Average Vessels Length`) * 1.1), 
               size = 1.2) +
  geom_text(aes(x = 1.5, y = max(cd31_tumor$`Average Vessels Length`) * 1.2), 
            label = round(get_pval(aov_tumor_mean_vessels_length), 4)) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Average Vessels Length (um)") +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))


aov(`Mean E Lacunarity` ~ group, data = cd31_tumor) %>% summary
p_tumor_lacunarity <- cd31_tumor %>% 
  select(group, mean_e_lacunarity = `Mean E Lacunarity`) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         mean = mean(mean_e_lacunarity), 
         se = sd(mean_e_lacunarity)/sqrt(n - 1)) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = mean_e_lacunarity), width = 0.2) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Lacunarity") +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))



aov(end_points_density ~ group, data = end_points_density) %>% summary
p_tumor_end_points_density <- cd31_tumor %>% 
  select(group, explant_area = `Explant area`, number_of_end_points = `Total Number of End Points`) %>% 
  group_by(group) %>% 
  mutate(n = n(), 
         end_points_density = round(number_of_end_points / explant_area, 4),
         mean = mean(end_points_density), 
         se = sd(end_points_density)/sqrt(n - 1)) %>>% 
    (~ end_points_density) %>% 
  ggplot(aes(group, mean)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_jitter(aes(y = end_points_density), width = 0.2) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "end points density") +
  theme_classic() +
  theme(axis.title.y = element_text(size = 8))
```


```{r}
p_tumor_cd31_percentage +
  p_tumor_mean_vessels_length +
  p_tumor_junction_density +
  # p_tumor_end_points_density +
  p_tumor_lacunarity +
  plot_annotation(title = "intro tumor", 
                  theme = theme(plot.title = element_text(hjust = 0.5, size = 20)))

ggsave("G:/data/kidney/Tumor/PB3/res-microscope/PB3-CD31-tumor.tiff", width = 10, height = 7)
```








