---
title: "Pdgfr-downstream-signals"
author: "YinCY"
date: "5/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidygraph)
library(tidyverse)
library(ggraph)
library(igraph)
library(EnsDb.Mmusculus.v79)
```

# Pdgfr downstream signals
```{r}
# all_path_df <- read.csv(file = "../res/P2ry12/all_pathways_df.csv", 
#                         stringsAsFactors = F)
all_path_df <- readRDS("../../P2y12r-and-C1q/data/KEGG/KEGG_pathways_formatted.rds")
names_to_display <- readRDS("../../P2y12r-and-C1q/data/KEGG/names_to_display.rds")

all_path_df %>% dim()
all_path_df %>% pull(type) %>% table()
all_path_df %>% pull(subtype) %>% table()

all_path_df %>% head()
all_path_df <- all_path_df %>% distinct(from, to, .keep_all = T)
all_path_df %>% dim()

all_path_df %>% 
  dplyr::filter(type == "maplink")

all_path_df <- all_path_df %>% 
  dplyr::filter(type != "maplink")
all_path_df %>% dim()

all_path_df$from <- gsub("mmu:", replacement = "", all_path_df$from)
all_path_df$to <- gsub("mmu:", replacement = "", all_path_df$to)

all_path_df %>% dim()
all_path_df %>% head()
```

```{r}
ig <- graph_from_data_frame(d = all_path_df, directed = T)

mapIds(EnsDb.Mmusculus.v79, 
       keys = c("Pdgfra", "Pdgfrb", "Pdgfrc"), 
       keytype = "SYMBOL", 
       column = "ENTREZID")

spath_Pdgfr <- shortest_paths(ig, 
                            from = V(ig)$name %in% c("18596"),
                            output = "epath", 
                            mode = "out") %>% 
  .$epath

spath_df_Pdgfr <- spath_Pdgfr %>% 
  sapply(as_ids) %>% 
  lapply(as.matrix) %>% 
  unlist() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames("from_to") %>% 
  separate(col = "from_to", into = c("from", "to"), sep = "\\|") %>% 
  distinct(from, to)

spath_df_Pdgfr_KEGG <- left_join(spath_df_Pdgfr, all_path_df, 
                                 by = c("from" = "from", "to" = "to")) %>% 
  distinct(from, to, .keep_all = T)
```

```{r}
N <- data.frame(
  id = c(spath_df_Pdgfr_KEGG$from, spath_df_Pdgfr_KEGG$to) %>% unique()
) %>% 
  mutate(
    shape = ifelse(grepl("^cpd|^gl|^dr", id, ignore.case = T), 22, 21)
  )

E <- spath_df_Pdgfr_KEGG

g <- tbl_graph(nodes = N, edges = E, directed = T)
```

```{r, message=FALSE}
set.seed(111)
g %>% 
  mutate(shape = factor(shape, levels = c(21, 22)), 
         ncol = ifelse(id %in% c("18596", "68797"), "tomato", "grey"), 
         name = names_to_display[id], 
         dist_pdgfrb = bfs_dist(root = .N()$name == "Pdgfrb", mode = "out")) %>% 
  dplyr::filter(name == "Lrp1")
  dplyr::filter(!is.na(dist_pdgfrb), dist_pdgfrb < 3) %>% 
  activate(edges) %>% 
  mutate(lty = factor(lty)) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == 30), 
                     edge_linetype = lty, 
                     label = edge_label), 
                 end_cap = circle(1.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(0.5, "mm")), 
                 edge_width = 0.1, 
                 label_size = 0.7) +
  geom_edge_link(aes(filter = (angle == 90), 
                     edge_linetype = lty, 
                     label = edge_label),
                 end_cap = circle(1.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 arrow = arrow(length = unit(0.5, "mm")), 
                 edge_width = 0.1, 
                 label_size = 0.7) +
  geom_edge_link(aes(filter = (is.na(angle)), 
                     edge_linetype = lty, 
                     label = edge_label), 
                 end_cap = circle(1.5, "mm"), 
                 start_cap = circle(1, "mm"), 
                 edge_width = 0.1, 
                 label_size = 0.7) +
  geom_node_point(aes(shape = shape, color = ncol), size = 2) +
  geom_node_text(aes(label = name), size = 0.8) +
  scale_color_manual(name = NULL, values = c("tomato" = "tomato", "grey" = "grey")) +
  guides(edge_linetype = "none", shape = "none", col = "none") +
  theme_graph()

ggsave("../../tumor-macrophage/Pdgfr-downstream-signal.pdf", width = 10, height = 10, limitsize = F)
```

# Pdgfrb Lrp1
```{r}
Pdgfrb_Lrp1 <- shortest_paths(graph = ig, 
                              from = V(ig)$name == "16971", 
                              to = V(ig)$name == "18596", 
                              mode = "all", 
                              output = "epath") %>% 
  .$epath


spath_df_Pdgfrb_lrp1 <- Pdgfrb_Lrp1 %>% 
  sapply(as_ids) %>% 
  lapply(as.matrix) %>% 
  unlist() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames("from_to") %>% 
  separate(col = "from_to", into = c("from", "to"), sep = "\\|") %>% 
  distinct(from, to)

spath_df_pdgfrb_lrp1_kegg <- left_join(spath_df_Pdgfrb_lrp1, all_path_df, 
                                       by = c("from" = "from", "to" = "to")) %>% 
  distinct(from, to, .keep_all = T)

N <- data.frame(
  id = c(spath_df_pdgfrb_lrp1_kegg$from, spath_df_pdgfrb_lrp1_kegg$to) %>% unique()
) %>% 
  mutate(
    name = names_to_display[id], 
    shape = ifelse(grepl("^cpd|^gl|^dr", id, ignore.case = T), 22, 21)
  )

E <- spath_df_pdgfrb_lrp1_kegg

g <- tbl_graph(nodes = N, edges = E, directed = T, node_key = "id")
```

```{r}
g %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(arrow = arrow(length = unit(2, "mm")), 
                 end_cap = circle(5, "mm")) +
  geom_node_point(size = 10, color = "grey") +
  geom_node_text(aes(label = name))
```





