---
title: "tumor-angiogenesis"
author: "yincy"
date: "5/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(magrittr)
library(tidyverse)
```


# endogenous inhibitors of angiogenesis
```{r}
matrix_derived <- c("Col4a1", "Hspg2", "Col18a1", 
                    "Fn1", "Itga5", "Itgb1", 
                    "Fbln5", "Thbs1", "Thbs2")

cell_and_blood_derived <- c("Ifng", "Ifnk", "Ifnb1", 
                            "Ifna15", "Ifna14", "Ifna-ps1", 
                            "Ifna9", "Ifna12", "Ifna13", 
                            "Ifna16", "Ifna2", "Ifnab", 
                            "Ifnz", "Ifna7", "Ifna11", 
                            "Ifna6", "Ifna5", "Ifna4", 
                            "Ifna1", "Ifne", "Ifnl2", "Ifnl3", 
                            "Il1b", "Il4", "Il12a", 
                            "Il12b", "Il18", "Serpinf1", 
                            "Plg", "F2", "Serpinc1", 
                            "Pf4")
others <- c("Timp1", "Timp2", "Timp4", 
            "Timp3", "Lect1", "Hsd17b7", 
            "Hsd17b6", "Hsd17b1", "Hsd17b3",
            "Hsd17b4", "Hsd17b12", "Hsd17b13",
            "Hsd17b11", "Hsd17b14", "Hsd17b2",
            "Hsd17b10", "Prl", "Mmp2", 
            "Flt1", "Tnni3", "Calr3")

anti_angio_df <- data.frame(
    symbol = c(matrix_derived, cell_and_blood_derived, others), 
    origin = c(rep("matrix_derived", length(matrix_derived)), 
               rep("cell_and_blood_derived", length(cell_and_blood_derived)), 
               rep("others", length(others)))
)
anti_angio_df$ensembl <- mapIds(EnsDb.Mmusculus.v79, 
                                keys = anti_angio_df$symbol, 
                                keytype = "SYMBOL", 
                                column = "GENEID")

saveRDS(anti_angio_df, "data/anti-angiogenesis.rds")
```


```{r}
anti_angio_df$symbol <- convert_mouse_to_human_symbols(anti_angio_df$symbol)
anti_angio_df <- anti_angio_df %>% dplyr::filter(!is.na(symbol))

anti_angio_df$ensembl <- mapIds(EnsDb.Hsapiens.v86, 
                                keys = anti_angio_df$symbol, 
                                keytype = "SYMBOL", 
                                column = "GENEID")
saveRDS(object = anti_angio_df, "data/anti-angiogenesis.rds")
```


# add cell meta data
```{r}
cell <- cell_annotation[, "cell"]
cluster_name <- cell_annotation[, "cluster_name"]
names(cluster_name) <- cell
cluster_name <- cluster_name[ccrcc[[]] %>% rownames()]
```

```{r}
ccrcc <- AddMetaData(ccrcc, metadata = cluster_name, col.name = "cell_name")
```


```{r}
ccrcc[[]] %>% 
    .[, c("type", "cell_name")] %>% 
    table %>% as.data.frame() %>% 
    ggplot(aes(type, Freq)) + 
    geom_bar(aes(fill = cell_name), position = "fill", stat = "identity") + 
    scale_fill_viridis(discrete = T, option = "H") +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = NULL)
```

# subset TAM
```{r}
cells_to_select <- ccrcc[[]] %>% 
    select(cell, cluster, cell_name) %>% 
    filter(grepl("^TAM", cell_name, ignore.case = F)) %>% 
    filter(!grepl("Ambiguos", cell_name, ignore.case = F)) %>% 
    pull(cell)

sce.TAM <- subset(ccrcc, cells = cells_to_select)
```

```{r}
DimPlot(sce.TAM, 
        reduction = "umap", 
        label = T, 
        group.by = "cell_name", 
        label.size = 2, 
        repel = T)
```

```{r}
saveRDS(ccrcc, "/home/yincy/git/Data/kidney/ccRCC/ccRCC_6pat_Seurat.rds")
```



